name: LiquiQuali
description: Aplicação para a análise da turbidez da água

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  camera:
  path_provider:
  permission_handler:
  shared_preferences:
  exif:
  animator: ^1.0.0+5

dev_dependencies:
   flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
